//! Pins the diff pixel counts against pixelmatch.
//!
//! The fixtures and the expected counts under `tests/fixtures` are generated by
//! `tools/fixtures/generate.mjs`. A change that moves any of these counts
//! changes what callers see for the thresholds they already configured, so it
//! needs a decision recorded in `docs/design.md` before the numbers are
//! regenerated.
//!
//! The counts hold even though pixelmatch computes in double precision and
//! this crate in single: the pixel sitting closest to a threshold clears it by
//! 5e-5 of the threshold, which leaves room for the rounding difference.
//! Reordering the arithmetic keeps the same margin to spend.

use std::fs::File;
use std::io::BufReader;
use std::path::{Path, PathBuf};

use pixeldelta_core::{compare, CompareOptions, Image, Verdict};

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

/// Decoded RGBA8 pixels of a fixture.
struct Decoded {
    width: u32,
    height: u32,
    data: Vec<u8>,
}

fn decode(path: &Path) -> Decoded {
    let mut decoder = png::Decoder::new(BufReader::new(
        File::open(path).expect("fixture is readable"),
    ));
    decoder.set_transformations(png::Transformations::ALPHA | png::Transformations::EXPAND);
    let mut reader = decoder.read_info().expect("fixture is a PNG");
    let mut data = vec![0; reader.output_buffer_size().expect("size fits in memory")];
    let info = reader.next_frame(&mut data).expect("fixture decodes");
    assert_eq!(
        (info.color_type, info.bit_depth),
        (png::ColorType::Rgba, png::BitDepth::Eight),
        "{} did not decode to RGBA8",
        path.display()
    );
    data.truncate(info.buffer_size());
    Decoded {
        width: info.width,
        height: info.height,
        data,
    }
}

/// One `fixture threshold aa diff_pixels` row of `expected.txt`.
struct Expectation {
    fixture: String,
    threshold: f32,
    detect_antialiasing: bool,
    diff_pixels: u64,
}

fn expectations() -> Vec<Expectation> {
    let text = std::fs::read_to_string(fixtures_dir().join("expected.txt"))
        .expect("expected.txt is readable");
    text.lines()
        .filter(|line| !line.starts_with('#') && !line.trim().is_empty())
        .map(|line| {
            let mut fields = line.split('\t');
            let mut next = || {
                fields
                    .next()
                    .unwrap_or_else(|| panic!("malformed row: {line}"))
            };
            Expectation {
                fixture: next().to_string(),
                threshold: next().parse().expect("threshold parses"),
                detect_antialiasing: match next() {
                    "on" => true,
                    "off" => false,
                    other => panic!("unknown aa column {other}"),
                },
                diff_pixels: next().parse().expect("diff pixel count parses"),
            }
        })
        .collect()
}

#[test]
fn diff_pixel_counts_match_pixelmatch() {
    let expectations = expectations();
    assert!(!expectations.is_empty(), "expected.txt has no rows");

    for expected in &expectations {
        let dir = fixtures_dir().join(&expected.fixture);
        let base = decode(&dir.join("base.png"));
        let head = decode(&dir.join("head.png"));
        let a = Image::from_rgba8(base.width, base.height, &base.data).expect("base wraps");
        let b = Image::from_rgba8(head.width, head.height, &head.data).expect("head wraps");

        let result = compare(
            &a,
            &b,
            &CompareOptions {
                threshold: expected.threshold,
                detect_antialiasing: expected.detect_antialiasing,
                ..CompareOptions::default()
            },
        );
        let case = format!(
            "{} at threshold {} with aa {}",
            expected.fixture, expected.threshold, expected.detect_antialiasing
        );

        assert_eq!(result.diff_pixels, expected.diff_pixels, "{case}");
        assert_eq!(
            result.verdict,
            if expected.diff_pixels == 0 {
                Verdict::Match
            } else {
                Verdict::Differ
            },
            "{case}"
        );
    }
}

#[test]
fn every_fixture_compares_equal_to_itself() {
    for expected in expectations() {
        let base = decode(&fixtures_dir().join(&expected.fixture).join("base.png"));
        let a = Image::from_rgba8(base.width, base.height, &base.data).expect("base wraps");

        let result = compare(
            &a,
            &a,
            &CompareOptions {
                threshold: 0.0,
                ..CompareOptions::default()
            },
        );

        assert_eq!(result.verdict, Verdict::Match, "{}", expected.fixture);
        assert_eq!(result.diff_pixels, 0, "{}", expected.fixture);
    }
}
