// The entry a bundler reaches through the `browser` field.
//
// It names pixeldelta-wasm rather than pixeldelta-wasm32-wasi, which holds the
// same build behind a `cpu: ["wasm32"]` a package manager will not install.
// browser.js beside this file says the latter and is regenerated by every napi
// build, so the field points here instead of at it.

export * from 'pixeldelta-wasm'
